version: "3"

services:
  backend:
    build: ./
    volumes:
      - output:/bin/output:rw
    networks:
      - outside

  frontend:
    build: ./frontend
    networks:
      - outside

volumes:
  output:

networks:
  outside: external
